# Generated by Django 6.0.5 on 2026-05-18 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('date_of_birth', models.DateField(verbose_name='Date de naissance')),
                ('cin', models.CharField(blank=True, max_length=20, null=True, verbose_name='CIN')),
                ('phone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Adresse')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ville')),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5, null=True, verbose_name='Groupe sanguin')),
                ('allergies', models.TextField(blank=True, verbose_name='Allergies')),
                ('chronic_diseases', models.TextField(blank=True, verbose_name='Maladies chroniques')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(verbose_name='Date et heure')),
                ('type', models.CharField(choices=[('Consultation', 'Consultation'), ('Bilan', 'Bilan'), ('Contrôle', 'Contrôle'), ('Urgence', 'Urgence'), ('Suivi', 'Suivi')], default='Consultation', max_length=20, verbose_name='Type de rendez-vous')),
                ('reason', models.TextField(verbose_name='Motif')),
                ('status', models.CharField(choices=[('Planifié', 'Planifié'), ('Annulé', 'Annulé'), ('Terminé', 'Terminé')], default='Planifié', max_length=20, verbose_name='Statut')),
                ('contacted_for_reminder', models.BooleanField(default=False, verbose_name='Contacté pour rappel')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='clinic.patient', verbose_name='Patient')),
            ],
            options={
                'verbose_name': 'Rendez-vous',
                'verbose_name_plural': 'Rendez-vous',
                'ordering': ['date_time'],
            },
        ),
    ]
